/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PanelConfiguraciones;

import java.awt.Color;
import utils.Sprite;
import Otros.*;

/**
 *
 * @author sando
 */
public class VentanaConfiguracion extends javax.swing.JFrame {
    Elemento newElemento;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName());

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
            
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConfiguracion = new javax.swing.JPanel();
        jpResultado = new javax.swing.JPanel();
        lblResultadosCaracteristicas = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        btnBando = new javax.swing.JToggleButton();
        cbxZombies = new javax.swing.JComboBox<>();
        cbxDefensas = new javax.swing.JComboBox<>();
        lblSeleccionarNombre = new javax.swing.JLabel();
        txfNombreComponente = new javax.swing.JTextField();
        btnCrearComponente = new javax.swing.JButton();
        lblTituloBando1 = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblAtackSpeed = new javax.swing.JLabel();
        lblAparicion = new javax.swing.JLabel();
        lblCoste = new javax.swing.JLabel();
        lblRango = new javax.swing.JLabel();
        txfDamage = new javax.swing.JTextField();
        txfAtackSpeed = new javax.swing.JTextField();
        txfVida = new javax.swing.JTextField();
        txfCoste = new javax.swing.JTextField();
        txfRango = new javax.swing.JTextField();
        txfAparicion = new javax.swing.JTextField();
        lblDamageError = new javax.swing.JLabel();
        lblVidaError = new javax.swing.JLabel();
        lblAparicionError = new javax.swing.JLabel();
        lblAtackSpeedError = new javax.swing.JLabel();
        lblCosteError = new javax.swing.JLabel();
        lblRangoError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblObjetivos = new javax.swing.JLabel();
        txfObjetivos = new javax.swing.JTextField();
        lblObjetivosError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(800, 800));

        jpConfiguracion.setBackground(new java.awt.Color(153, 255, 153));
        jpConfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jpResultado.setBackground(new java.awt.Color(255, 153, 102));
        jpResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(51, 0, 51)));

        lblResultadosCaracteristicas.setBackground(new java.awt.Color(255, 204, 204));
        lblResultadosCaracteristicas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblResultadosCaracteristicas.setOpaque(true);

        javax.swing.GroupLayout jpResultadoLayout = new javax.swing.GroupLayout(jpResultado);
        jpResultado.setLayout(jpResultadoLayout);
        jpResultadoLayout.setHorizontalGroup(
            jpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultadosCaracteristicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        jpResultadoLayout.setVerticalGroup(
            jpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadoLayout.createSequentialGroup()
                .addComponent(lblResultadosCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblTitulo.setText("Bienvenido a la customizacion de Defensas/Zombies para ZombiesTec");

        lblDamage.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblDamage.setText("Daño:");

        btnBando.setBackground(new java.awt.Color(255, 204, 0));
        btnBando.setText("Defensas");
        btnBando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBandoActionPerformed(evt);
            }
        });

        cbxZombies.setBackground(new java.awt.Color(0, 153, 0));
        cbxZombies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipos de Zombies", "Contacto por tierra", "Contacto Volador", "Mediano Alcance", "De choque" }));
        cbxZombies.setToolTipText("Hola");
        cbxZombies.setEnabled(false);
        cbxZombies.setVisible(false);
        cbxZombies.setName("Tipos de Zombies"); // NOI18N
        cbxZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxZombiesActionPerformed(evt);
            }
        });

        cbxDefensas.setBackground(new java.awt.Color(255, 204, 0));
        cbxDefensas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipos de defensa", "De contacto", "Mediano Alcance", "Defensa Aerea", "De impacto", "Mediano Alcance Multiple", "Muros de defensa"}));
        cbxDefensas.setToolTipText("");
        cbxDefensas.setName("Tipos de Defensa"); // NOI18N
        cbxDefensas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDefensasActionPerformed(evt);
            }
        });

        lblSeleccionarNombre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblSeleccionarNombre.setText("Seleccione el nombre de su nueva componente:");

        txfNombreComponente.setBackground(new java.awt.Color(204, 255, 204));
        txfNombreComponente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfNombreComponenteKeyReleased(evt);
            }
        });

        btnCrearComponente.setBackground(new java.awt.Color(255, 51, 51));
        btnCrearComponente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearComponente.setText("Crear componente");
        btnCrearComponente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 51), new java.awt.Color(153, 0, 51), new java.awt.Color(153, 0, 51), new java.awt.Color(153, 0, 51)));
        btnCrearComponente.setEnabled(false);
        btnCrearComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearComponenteActionPerformed(evt);
            }
        });

        lblTituloBando1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblTituloBando1.setText("Seleccione el bando al que desea agregar un nuevo componente:");

        lblVida.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblVida.setText("Vida:");

        lblAtackSpeed.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblAtackSpeed.setText("AtackSpeed:");

        lblAparicion.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblAparicion.setText("Nivel de aparición:");

        lblCoste.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblCoste.setText("Coste de capacidad:");

        lblRango.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblRango.setText("Rango:");
        lblRango.setVisible(false);

        txfDamage.setBackground(new java.awt.Color(204, 255, 204));
        txfDamage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfDamageKeyReleased(evt);
            }
        });

        txfAtackSpeed.setBackground(new java.awt.Color(204, 255, 204));
        txfAtackSpeed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfAtackSpeedKeyReleased(evt);
            }
        });

        txfVida.setBackground(new java.awt.Color(204, 255, 204));
        txfVida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfVidaKeyReleased(evt);
            }
        });

        txfCoste.setBackground(new java.awt.Color(204, 255, 204));
        txfCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfCosteKeyReleased(evt);
            }
        });

        txfRango.setBackground(new java.awt.Color(204, 255, 204));
        txfRango.setEnabled(false);
        txfRango.setVisible(false);
        txfRango.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfRangoKeyReleased(evt);
            }
        });

        txfAparicion.setBackground(new java.awt.Color(204, 255, 204));
        txfAparicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfAparicionKeyReleased(evt);
            }
        });

        lblDamageError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblDamageError.setForeground(new java.awt.Color(153, 51, 0));
        lblDamageError.setVisible(false);
        lblDamageError.setText("No es numero o se encuentra fuera del rango valido");

        lblVidaError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblVidaError.setForeground(new java.awt.Color(153, 51, 0));
        lblVidaError.setVisible(false);
        lblVidaError.setText("No es numero o se encuentra fuera del rango valido");

        lblAparicionError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblAparicionError.setForeground(new java.awt.Color(153, 51, 0));
        lblAparicionError.setVisible(false);
        lblAparicionError.setText("No es numero o se encuentra fuera del rango valido");

        lblAtackSpeedError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblAtackSpeedError.setForeground(new java.awt.Color(153, 51, 0));
        lblAtackSpeedError.setVisible(false);
        lblAtackSpeedError.setText("No es numero o se encuentra fuera del rango valido");

        lblCosteError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblCosteError.setForeground(new java.awt.Color(153, 51, 0));
        lblCosteError.setVisible(false);
        lblCosteError.setText("No es numero o se encuentra fuera del rango valido");

        lblRangoError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblRangoError.setForeground(new java.awt.Color(153, 51, 0));
        lblRangoError.setVisible(false);
        lblRangoError.setText("No es numero o se encuentra fuera del rango valido");

        lblNameError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(153, 51, 0));
        lblNameError.setText("No es un nombre valido");

        lblObjetivos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblObjetivos.setText("Objetivos:");
        lblObjetivos.setVisible(false);

        txfObjetivos.setBackground(new java.awt.Color(204, 255, 204));
        txfObjetivos.setEnabled(false);
        txfObjetivos.setVisible(false);
        txfObjetivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfObjetivosKeyReleased(evt);
            }
        });

        lblObjetivosError.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblObjetivosError.setForeground(new java.awt.Color(153, 51, 0));
        lblObjetivosError.setVisible(false);
        lblObjetivosError.setText("No es numero o se encuentra fuera del rango valido");

        javax.swing.GroupLayout jpConfiguracionLayout = new javax.swing.GroupLayout(jpConfiguracion);
        jpConfiguracion.setLayout(jpConfiguracionLayout);
        jpConfiguracionLayout.setHorizontalGroup(
            jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfiguracionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObjetivos)
                    .addComponent(lblRango)
                    .addComponent(lblAtackSpeed)
                    .addComponent(lblDamage)
                    .addComponent(lblCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAtackSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfRango, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVidaError)
                    .addComponent(lblAparicionError, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCosteError)
                    .addComponent(lblDamageError)
                    .addComponent(lblAtackSpeedError)
                    .addComponent(lblRangoError, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObjetivosError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(jpConfiguracionLayout.createSequentialGroup()
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBando))
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cbxDefensas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSeleccionarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfNombreComponente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameError))
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cbxZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpConfiguracionLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblTituloBando1)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );
        jpConfiguracionLayout.setVerticalGroup(
            jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfiguracionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnBando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addComponent(cbxDefensas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeleccionarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfNombreComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameError))
                        .addGap(18, 18, 18)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVida)
                            .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVidaError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAparicion)
                            .addComponent(lblAparicionError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoste)
                            .addComponent(txfCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCosteError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamage)
                            .addComponent(txfDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDamageError))
                        .addGap(5, 5, 5)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAtackSpeedError)
                            .addComponent(txfAtackSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAtackSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRangoError)
                            .addComponent(lblRango))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObjetivosError)
                            .addComponent(lblObjetivos)))
                    .addComponent(jpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnCrearComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpConfiguracionLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(lblTituloBando1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(678, Short.MAX_VALUE)))
        );

        cbxZombies.getAccessibleContext().setAccessibleName("");
        cbxZombies.getAccessibleContext().setAccessibleDescription("");
        cbxDefensas.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBandoActionPerformed
        if(btnBando.getText().equals("Zombies")){
            btnBando.setText("Defensas");
            btnBando.setBackground(new Color(255,204,0));
            cbxDefensas.setEnabled(true);
            cbxDefensas.setVisible(true);
            cbxZombies.setEnabled(false);
            cbxZombies.setVisible(false);
        } else{
            this.btnBando.setText("Zombies");
            this.btnBando.setBackground(new Color(0,153,0));
            cbxDefensas.setEnabled(false);
            cbxDefensas.setVisible(false);
            cbxZombies.setEnabled(true);
            cbxZombies.setVisible(true);
        }

        lblRango.setVisible(false);
        txfRango.setVisible(false);
        txfRango.setEnabled(false);
        lblObjetivos.setVisible(false);
        txfObjetivos.setVisible(false);
        txfObjetivos.setEnabled(false);
        lblDamage.setVisible(true);
        txfDamage.setVisible(true);
        txfDamage.setEnabled(true);
        lblAtackSpeed.setVisible(true);
        txfAtackSpeed.setVisible(true);
        txfAtackSpeed.setEnabled(true);
               
        
    }//GEN-LAST:event_btnBandoActionPerformed

    
    private void btnCrearComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComponenteActionPerformed
        
    }//GEN-LAST:event_btnCrearComponenteActionPerformed

    
    private void txfNombreComponenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNombreComponenteKeyReleased
        String textoLeido = txfNombreComponente.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
            
        if(esValido(textoLeido)){
            lblNameError.setVisible(false);
        } else{
            lblNameError.setVisible(true);
        }          
        //TODO verificar que no se repitan nombres de componentes en esValido()
    }//GEN-LAST:event_txfNombreComponenteKeyReleased

    private void txfDamageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfDamageKeyReleased
        String textoLeido = txfDamage.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblDamageError.setVisible(false);
        }else
            lblDamageError.setVisible(true);
    }//GEN-LAST:event_txfDamageKeyReleased

    private void txfVidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfVidaKeyReleased
        String textoLeido = txfVida.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblVidaError.setVisible(false);
        }else
            lblVidaError.setVisible(true);
    }//GEN-LAST:event_txfVidaKeyReleased

    private void txfAtackSpeedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfAtackSpeedKeyReleased
        String textoLeido = txfAtackSpeed.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblAtackSpeedError.setVisible(false);
        }else
            lblAtackSpeedError.setVisible(true);
    }//GEN-LAST:event_txfAtackSpeedKeyReleased

    private void txfAparicionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfAparicionKeyReleased
        String textoLeido = txfAparicion.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblAparicionError.setVisible(false);
        }else
            lblAparicionError.setVisible(true);
    }//GEN-LAST:event_txfAparicionKeyReleased

    private void txfRangoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfRangoKeyReleased
        String textoLeido = txfRango.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblRangoError.setVisible(false);
        }else
            lblRangoError.setVisible(true);
    }//GEN-LAST:event_txfRangoKeyReleased

    private void txfObjetivosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfObjetivosKeyReleased
        String textoLeido = txfObjetivos.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblObjetivosError.setVisible(false);
        }else
            lblObjetivosError.setVisible(true);
    }//GEN-LAST:event_txfObjetivosKeyReleased

    private void txfCosteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCosteKeyReleased
        String textoLeido = txfCoste.getText();
        
        if(textoLeido != null)
            textoLeido = textoLeido.trim();
          
        if(isNumeric(textoLeido) && Integer.parseInt(textoLeido) >= 0){
           lblCosteError.setVisible(false);
        }else
            lblCosteError.setVisible(true);
    }//GEN-LAST:event_txfCosteKeyReleased

    private void cbxDefensasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDefensasActionPerformed
        switch (cbxDefensas.getSelectedItem().toString()) {
            case "Mediano Alcance":
                lblRango.setVisible(true);
                txfRango.setVisible(true);
                txfRango.setEnabled(true);
                
                lblObjetivos.setVisible(false);
                txfObjetivos.setVisible(false);
                txfObjetivos.setEnabled(false);
                
                lblDamage.setVisible(true);
                txfDamage.setVisible(true);
                txfDamage.setEnabled(true);
                
                lblAtackSpeed.setVisible(true);
                txfAtackSpeed.setVisible(true);
                txfAtackSpeed.setEnabled(true);
                break;
            case "Mediano Alcance Multiple":
                lblRango.setVisible(true);
                txfRango.setVisible(true);
                txfRango.setEnabled(true);
                
                lblObjetivos.setVisible(true);
                txfObjetivos.setVisible(true);
                txfObjetivos.setEnabled(true);
                
                lblDamage.setVisible(true);
                txfDamage.setVisible(true);
                txfDamage.setEnabled(true);
                
                lblAtackSpeed.setVisible(true);
                txfAtackSpeed.setVisible(true);
                txfAtackSpeed.setEnabled(true);
                break;
            case "Muros de defensa":
                lblRango.setVisible(false);
                txfRango.setVisible(false);
                txfRango.setEnabled(false);
                
                lblObjetivos.setVisible(false);
                txfObjetivos.setVisible(false);
                txfObjetivos.setEnabled(false);
                
                lblDamage.setVisible(false);
                txfDamage.setVisible(false);
                txfDamage.setEnabled(false);
                
                lblAtackSpeed.setVisible(false);
                txfAtackSpeed.setVisible(false);
                txfAtackSpeed.setEnabled(false);
                break;
            default:
                lblRango.setVisible(false);
                txfRango.setVisible(false);
                txfRango.setEnabled(false);
                
                lblObjetivos.setVisible(false);
                txfObjetivos.setVisible(false);
                txfObjetivos.setEnabled(false);
                
                lblDamage.setVisible(true);
                txfDamage.setVisible(true);
                txfDamage.setEnabled(true);
                
                lblAtackSpeed.setVisible(true);
                txfAtackSpeed.setVisible(true);
                txfAtackSpeed.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_cbxDefensasActionPerformed

    private void cbxZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxZombiesActionPerformed
        switch (cbxDefensas.getSelectedItem().toString()) {
            case "Mediano Alcance":
                lblRango.setVisible(true);
                txfRango.setVisible(true);
                txfRango.setEnabled(true);
                break;
            default:
                lblRango.setVisible(false);
                txfRango.setVisible(false);
                txfRango.setEnabled(false);
                lblObjetivos.setVisible(false);
                txfObjetivos.setVisible(false);
                txfObjetivos.setEnabled(false); 
                break;
        }
    }//GEN-LAST:event_cbxZombiesActionPerformed

    
    
    private boolean esValido(String nombre){ //true si es valido, false si no es valido
        //TODO verificar que no se repitanlos nombres de componentes
        if(nombre.equals(""))
            return false;
        //}else if(nombre.equals("hola"))  //Se aplicaria para todas las clases mas hijas que hay
        return true;
        //return false;
    }
    
    private boolean isNumeric(String str){
        try {
            int numero = Integer.parseInt(str);
            return true;
        } catch (Exception e) {
            return false;
        }
    }    
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaConfiguracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBando;
    private javax.swing.JButton btnCrearComponente;
    private javax.swing.JComboBox<String> cbxDefensas;
    private javax.swing.JComboBox<String> cbxZombies;
    private javax.swing.JPanel jpConfiguracion;
    private javax.swing.JPanel jpResultado;
    private javax.swing.JLabel lblAparicion;
    private javax.swing.JLabel lblAparicionError;
    private javax.swing.JLabel lblAtackSpeed;
    private javax.swing.JLabel lblAtackSpeedError;
    private javax.swing.JLabel lblCoste;
    private javax.swing.JLabel lblCosteError;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblDamageError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblObjetivos;
    private javax.swing.JLabel lblObjetivosError;
    private javax.swing.JLabel lblRango;
    private javax.swing.JLabel lblRangoError;
    private javax.swing.JLabel lblResultadosCaracteristicas;
    private javax.swing.JLabel lblSeleccionarNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloBando1;
    private javax.swing.JLabel lblVida;
    private javax.swing.JLabel lblVidaError;
    private javax.swing.JTextField txfAparicion;
    private javax.swing.JTextField txfAtackSpeed;
    private javax.swing.JTextField txfCoste;
    private javax.swing.JTextField txfDamage;
    private javax.swing.JTextField txfNombreComponente;
    private javax.swing.JTextField txfObjetivos;
    private javax.swing.JTextField txfRango;
    private javax.swing.JTextField txfVida;
    // End of variables declaration//GEN-END:variables
}

