/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

/**
 *
 * @author andre
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulojuego = new javax.swing.JLabel();
        ButtonJugar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        ButtonEditor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        Titulojuego.setText("Zombies juego omg");

        ButtonJugar.setText("Jugar");
        ButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJugarActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");

        ButtonEditor.setText("Editor");
        ButtonEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(184, 184, 184)
                                                .addComponent(Titulojuego))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(201, 201, 201)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ButtonSalir)
                                                        .addComponent(ButtonJugar)
                                                        .addComponent(ButtonEditor))))
                                .addContainerGap(215, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(Titulojuego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77,
                                        Short.MAX_VALUE)
                                .addComponent(ButtonJugar)
                                .addGap(9, 9, 9)
                                .addComponent(ButtonEditor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonSalir)
                                .addGap(137, 137, 137)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEditorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonEditorActionPerformed
        // Abrir el Editor de Configuración
        PanelConfiguraciones.VentanaConfiguracion editor = new PanelConfiguraciones.VentanaConfiguracion();
        editor.setVisible(true);
        this.dispose(); // Cerrar el menú principal
    }// GEN-LAST:event_ButtonEditorActionPerformed

    private void ButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonJugarActionPerformed
        // Abrir la ventana de Partidas
        Partidas partidas = new Partidas();
        partidas.setVisible(true);
        this.dispose(); // Cerrar el menú principal
    }// GEN-LAST:event_ButtonJugarActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonSalirActionPerformed
        // Salir de la aplicación
        System.exit(0);
    }// GEN-LAST:event_ButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditor;
    private javax.swing.JButton ButtonJugar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel Titulojuego;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
