/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

/**
 *
 * @author andre
 */
public class Partidas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Partidas.class.getName());

    /**
     * Creates new form Partidas
     */
    public Partidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        TextoPartidasGuardadas = new javax.swing.JLabel();
        PanelSaves = new javax.swing.JPanel();
        ButtonNuevaPartida = new javax.swing.JButton();
        ButtonCargarPartida = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(255, 153, 153));

        TextoPartidasGuardadas.setText("Partidas guardadas");

        PanelSaves.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout PanelSavesLayout = new javax.swing.GroupLayout(PanelSaves);
        PanelSaves.setLayout(PanelSavesLayout);
        PanelSavesLayout.setHorizontalGroup(
                PanelSavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        PanelSavesLayout.setVerticalGroup(
                PanelSavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 261, Short.MAX_VALUE));

        ButtonNuevaPartida.setText("Nueva Partida");
        ButtonNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevaPartidaActionPerformed(evt);
            }
        });

        ButtonCargarPartida.setText("Cargar Partida");
        ButtonCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCargarPartidaActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
                PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelFondoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PanelSaves, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelFondoLayout.createSequentialGroup()
                                                .addComponent(TextoPartidasGuardadas)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(PanelFondoLayout.createSequentialGroup()
                                                .addComponent(ButtonNuevaPartida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ButtonCargarPartida)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        160, Short.MAX_VALUE)
                                                .addComponent(ButtonSalir)))
                                .addContainerGap()));
        PanelFondoLayout.setVerticalGroup(
                PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextoPartidasGuardadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelSaves, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ButtonNuevaPartida)
                                                .addComponent(ButtonCargarPartida)
                                                .addComponent(ButtonSalir))
                                .addContainerGap(36, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonNuevaPartidaActionPerformed
        // Abrir la interfaz de juego
        InterfazJuego juego = new InterfazJuego();
        juego.setVisible(true);
        this.dispose(); // Cerrar la ventana de partidas
    }// GEN-LAST:event_ButtonNuevaPartidaActionPerformed

    private void ButtonCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonCargarPartidaActionPerformed
        // Funcionalidad para cargar partida (por implementar)
        javax.swing.JOptionPane.showMessageDialog(this,
                "Funcionalidad de cargar partida aún no implementada",
                "Información",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_ButtonCargarPartidaActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonSalirActionPerformed
        // Volver al menú principal
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose(); // Cerrar la ventana de partidas
    }// GEN-LAST:event_ButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Partidas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCargarPartida;
    private javax.swing.JButton ButtonNuevaPartida;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelSaves;
    private javax.swing.JLabel TextoPartidasGuardadas;
    // End of variables declaration//GEN-END:variables
}
